linters:
  PropertySortOrder:
    enabled: false

  VendorPrefix:
    enabled: false

  NestingDepth:
    max_depth: 5

  SelectorDepth:
    max_depth: 5

  SelectorFormat:
    convention: hyphenated_BEM

  PlaceholderInExtend:
    enabled: false
